const GET_BANNERS="GET_BANNERS"
const GET_ONELEVELCATEGORYLIST="GET_ONELEVELCATEGORYLIST"
const GET_MODULES="GET_MODULES"
const GET_MODULES1="GET_MODULES1"
const GET_MODULES2="GET_MODULES2"

export default {
	GET_BANNERS,
	GET_ONELEVELCATEGORYLIST,
	GET_MODULES,
	GET_MODULES1,
	GET_MODULES2
}